name: "huggingface_t5_translation"
backend: "python"

input [{ name: "INPUT0", data_type: TYPE_STRING, dims: [-1]}]
output [{ name: "OUTPUT0", data_type: TYPE_STRING, dims: [-1]}]

instance_group [{ count: 1, kind: KIND_CPU }]