name: "category_tensorflow_model"
platform: "tensorflow_savedmodel"
max_batch_size: 0

parameters: {
    key: "TF_SIGNATURE_DEF"
    value: {
        string_value: "call"
    }
}

input [
  {
    name: "candidates"
    data_type: TYPE_FP32
    dims: [ -1 , -1]

  }
]
input [
  {
    name: "user_history"
    data_type: TYPE_FP32
    dims: [ -1 , -1]

  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

instance_group [
    {
      count: 2
      kind: KIND_CPU
    }
  ]

dynamic_batching { }